version: '3'

services:
  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /server